# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('starship_class', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('length', models.FloatField(blank=True, null=True)),
                ('hyperdrive_rating', models.FloatField(blank=True, null=True)),
                ('cargo_capacity', models.BigIntegerField(blank=True, null=True)),
                ('crew', models.IntegerField(blank=True, null=True)),
                ('passengers', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='ship_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='shiptrader.Starship'),
        ),
    ]
