version: '3'

services:
  code-test:
    build:
      context: .
    volumes:
      - .:/srv/python-code-test
    ports:
      - '8008:8008'
    depends_on:
      - postgresql
    # command: 'python manage.py runserver 0.0.0.0:8008'
    # NOTE: uncomment to debug container
    command: /bin/sh -x -c 'while true; do sleep 60; done'

  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
